### ISSUE TITLE
Mask from right not working in landscape mode

### ISSUE THREAD

**Issue by smamczak** [Bruce-pac/SlideDrawer#3]
Mask from left works fine but mask from right has an issue

![Simulator Screen Shot - iPhone XR - 2020-02-19 at 11 41 05](https://user-images.githubusercontent.com/17873294/74827003-e67ebd00-530c-11ea-876f-08895aa7c31d.png)

**Comment by Bruce-pac** [comment]
@smamczak thanks. I have fixed it and SlideDrawer 2.0.0 is born.
