### ISSUE TITLE
compile time error in Base class

### ISSUE THREAD

**Issue by jesuasir007** [Bruce-pac/SlideDrawer#7]
Candidate has non-matching type 'SlideDrawer<Self>' [with CompatibleType = UIViewController.CompatibleType]

public protocol SlideDrawerCompatible {
    /// Extended type
    associatedtype CompatibleType

    var sd: SlideDrawer<CompatibleType> { get }
}

public extension SlideDrawerCompatible {
    var sd: SlideDrawer<Self> {
        print(self)
        return SlideDrawer(self)
    }
}

extension UIViewController: SlideDrawerCompatible {}
extension UIView: SlideDrawerCompatible {}

**Comment by jesuasir007** [comment]
import Foundation
import UIKit

// SlideDrawer struct
public struct SlideDrawer<Base> {
    /// Base object to extend.
    public let base: Base

    /// Creates extensions with base object.
    ///
    /// - parameter base: Base object.
    public init(_ base: Base) {
        self.base = base
    }
}

// SlideDrawerCompatible protocol with a generic type
public protocol SlideDrawerCompatible {
    associatedtype CompatibleType
    var sd: SlideDrawer<CompatibleType> { get }
}

// Default implementation for SlideDrawerCompatible
public extension SlideDrawerCompatible where Self: AnyObject {
    var sd: SlideDrawer<Self> {
        return SlideDrawer(self)
    }
}

// UIViewController conforms to SlideDrawerCompatible
extension UIViewController: SlideDrawerCompatible {
    public typealias CompatibleType = UIViewController
}

// UIView conforms to SlideDrawerCompatible
extension UIView: SlideDrawerCompatible {
    public typealias CompatibleType = UIView
}

// Extension to get the parent UIViewController from a UIView
extension SlideDrawer where Base: UIView {
    public var viewController: UIViewController? {
        var responder = self.base.next
        while responder != nil && !(responder?.isKind(of: UIViewController.self))! {
            responder = responder?.next
        }
        let result = responder.map { $0 as! UIViewController }
        return result
    }
}

// NSNotification.Name extension
extension NSNotification.Name {
    public struct SlideDrawer {
        @available(*, deprecated, message: "No longer needed")
        public static let insideDismissCompleted = Notification.Name("insideDismissCompleted")
    }
}

**Comment by Bruce-pac** [comment]
I fixed some issues with the latest Xcode and Swift 5.10. It didn't happen as you said.
The changes were committed to the dev branch.You can check it.
What version of Swift are you using？

**Comment by jesuasir007** [comment]
ah ok
